[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd QuiltCalc && npm install']

[phases.build]
cmds = ['cd QuiltCalc && npx expo export --platform web']

[start]
cmd = 'cd QuiltCalc && npx serve dist/expo -l ${PORT:-8081} -s'
