[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx expo export --platform web']

[start]
cmd = 'npx serve dist -l tcp://0.0.0.0:${PORT:-8081} -s'
