[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd QuiltCalc && npm install']

[start]
cmd = 'cd QuiltCalc && EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 npx expo start --web --port ${PORT:-8081}'
